### ISSUE TITLE
Returning 1 binary column 

### ISSUE THREAD

**Issue by rowanwins** [ooxif/laravel-query-param#1]
Hi there,

Thanks for what looks like a promising extension. I was just wondering how you'd suggest writing an eloquent query where I only want to return one of the fields as binary.

In my model I've added 

```
    protected $casts = [
        'startPoint' => 'binary',
    ];
```

Now Im trying to write something in my controller that passes back all the values for the record including the one field that is binary. Do I need to do something special here?

```
Model::find($id);
```

Thanks in advance,
Rowan

PS Sorry if this is a rookie question :)

**Comment by ooxif** [comment]
Hi Rowan

If you'd like to use a binary column as a primary key, try below

``` php
class Foo extends Eloquent
{
    use \Ooxif\LaravelQueryParam\ModelTrait;

    protected $primaryKey = 'startPoint'; // $primaryKey is set to 'id' by default.

    public $incrementing = false; // true by default

    protected $casts [
        'startPoint' => 'binary',
    ];
}

$foo = Foo::find(param_lob('some binary data'));
// or
$fooCollection = Foo::find([param_lob('data A'), param_lob('data B')]);
```

or, if you'd like to fetch just one binary column, try

``` php
$model = Model::find($id, ['startPoint']); // pass an array of fields which you'd like to fetch
$model->startPoint; // object(Ooxif\LaravelQueryParam\Param\ParamLob)

// or
$binaryData = DB::table('table_name')->where('startPoint', param_lob('some binary data'))->pluck('startPoint');
$binaryData === 'some binary data'; // true
```

**Comment by rowanwins** [comment]
Hi @ooxif , thanks for the response, that was helpful
